name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
      contents: read

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
          cache: yarn

      - name: "Install dependencies"
        run: yarn install --frozen-lockfile

      - name: "Build"
        run: yarn build

      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: "dist/"

      - name: "Deploy"
        id: deployment
        uses: actions/deploy-pages@v1
